CREATE TABLE IF NOT EXISTS vcs_bookings (
  reference VARCHAR(64) PRIMARY KEY,
  idempotency_key CHAR(64) NOT NULL UNIQUE,
  batch_id VARCHAR(160) NOT NULL,
  payment_id VARCHAR(255) UNIQUE NULL,
  payment_status VARCHAR(32) NOT NULL,
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vcs_processed_events (
  event_id VARCHAR(255) PRIMARY KEY,
  event_type VARCHAR(120) NOT NULL,
  processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
